# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"        
  #config.vm.network "forwarded_port", guest: 3306, host: 3306
  config.vm.network "private_network", ip: "192.168.56.10"
  #config.vm.network "public_network"
  #config.vm.network "public_network", ip: "192.168.31.100"

  #config.vm.provision :shell, inline: "sudo mkdir -p /home/vagrant/docker_data"
  
  config.vm.synced_folder "/Users/jiuwu.liu/docker_data", "/home/vagrant/docker_data", type: "nfs", nfs_export: true

  config.vm.provision "docker" do |doc|         
    doc.run "mysql", image: "mysql:5.7", args: "--privileged -p 3306:3306 -v /home/vagrant/docker_data/mysql/data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=123456"         
  end    
end