# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"        
  #config.vm.network "forwarded_port", guest: 80, host: 9000
  #config.vm.network "private_network", ip: "192.168.56.10"
  #config.vm.network "public_network"
  #config.vm.network "public_network", ip: "192.168.31.100"
  config.vm.network "public_network", ip: "192.168.56.5"

  config.vm.provision "docker",images: ["nginx:latest"] do |doc|         
    doc.run "nginx", args: "-p 80:80"        
  end    
end