# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # 配置负载均衡器     
  config.vm.define "lb1" do |lb1|   
    lb1.vm.box = "ubuntu/xenial64"     
    lb1.vm.network "private_network", ip: "192.168.56.200"
    lb1.vm.provision :shell do |shell|             
      shell.path = "lb.sh"         
    end
  end    
  # 配置第一个Web机器     
  config.vm.define "web1" do |web1|  
    web1.vm.box = "ubuntu/xenial64"     
    web1.vm.network "private_network", ip: "192.168.56.201"
    web1.vm.provision :shell do |shell|             
      shell.args = "1"             
      shell.path = "web.sh"     
    end
  end    
  # 配置第二个Web机器   
  config.vm.define "web2" do |web2|   
    web2.vm.box = "ubuntu/xenial64"     
    web2.vm.network "private_network", ip: "192.168.56.202"
    web2.vm.provision :shell do |shell|             
      shell.args = "2"             
      shell.path = "web.sh"     
    end
  end
end
